export { default as About} from "./About"
export { default as Cheapest } from "./Cheapest"
export { default as Contact } from "./Contact"
export { default as Home } from "./Home"
export { default as Popular } from "./Popular"
export { default as results } from "./result"